//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanDuLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoanDuLich()
        {
            this.KhachTheoDoans = new HashSet<KhachTheoDoan>();
        }
    
        public int MaDoan { get; set; }
        public string TenDoan { get; set; }
        public Nullable<int> MaTour { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string MoTa { get; set; }
        public int TinhTrang { get; set; }
        public Nullable<int> MaGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachTheoDoan> KhachTheoDoans { get; set; }
        public virtual GiaTour GiaTour { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
