//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachTheoDoan
    {
        public int MaDoan { get; set; }
        public int MaKhachHang { get; set; }
        public bool Chitiet { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
