//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.DiaDiemThamQuans = new HashSet<DiaDiemThamQuan>();
            this.DoanDuLiches = new HashSet<DoanDuLich>();
            this.GiaTours = new HashSet<GiaTour>();
        }
    
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> LoaiTour { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> SoDem { get; set; }
        public string Mua { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaDiemThamQuan> DiaDiemThamQuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanDuLich> DoanDuLiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaTour> GiaTours { get; set; }
        public virtual LoaiTour LoaiTour1 { get; set; }
    }
}
